language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt -t vendor"
# command to run tests
script: "python manage.py test"

services:
  - mysql
sudo: true
before_script:
  - mysql -e 'CREATE DATABASE ntxuva2;'
