version: 1
disable_existing_loggers: true

formatters:
    simple:
        format: '%(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)d]'
        datefmt: '%Y-%m-%d %H:%M:%S'
    full:
        format: '
            Message type:       %(levelname)s
            Location:           %(pathname)s:%(lineno)d
            Module:             %(module)s
            Function:           %(funcName)s
            Time:               %(asctime)s

            Message:

            %(message)s
        '
        datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
    console:
        class: logging.StreamHandler
        formatter: simple
        level: DEBUG
        stream: ext://sys.stdout
    file:
        class : logging.handlers.RotatingFileHandler
        formatter: simple
        level: DEBUG
        filename: mopa/data/logs/mopa.log
        maxBytes: 10485760 # 10 MB
        backupCount: 10
        encoding: utf8

loggers:
    console:
        level: DEBUG
        handlers: [console]
        propagate: no
    file:
        level: INFO
        handlers: [file]
        propagate: no

root:
    level: DEBUG
    handlers: [console, file]
